### PR TITLE
fixing type of clinVarIds

### PR DESCRIPTION
**Pull request by mbaudis**
Thanks to @mrueda for pointing this out https://github.com/ga4gh-beacon/beacon-v2-Models/issues/62

### CODE REVIEW

**Comment by jrambla** [comment]
Why is more than one ClinVarId necessary?

**Comment by mbaudis** [comment]
Good question - how came this in as multiple? Needed?

Apart from one or more: pseudoCamelCase (upper "V" in clinVarId) will require ugly "clin_var_id" on camel <-> snake round trips (thanks @rahelp); so should better be clinvarIds or clinvarId. Cosmetics, but ...

**Comment by mrueda** [comment]
The examples provided in the repo ("examples": ["RCV000009910.19", "9325", "VCV000009325.28"]) reflect the variety of identifiers that ClinVar accepts for a given variant. If all of these identifiers are going to be accepted, then the field should be named plural and set to "type" : "array".

https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/

Cheers,

m

**Comment by jrambla** [comment]
I'm guessing that there is a confusion here.
"`examples`" is a Json Schema keyword that allows you to put more than one example, as an array of them. It does not convey that the property is an array.
Hence, if we actually don't need more than one Id (and I guess I've checked that at that time, but not solid on it), then, we should stick to the current schema definition.

From the [JSON Schema website:](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=example)
The examples keyword is a place to provide an array of examples that validate against the schema. This isn’t used for validation, but may help with explaining the effect and purpose of the schema to a reader. Each entry should validate against the schema in which it resides, but that isn’t strictly required. There is no need to duplicate the default value in the examples array, since default will be treated as another example.

**Comment by mrueda** [comment]
Why is it named plural then?

**Comment by mbaudis** [comment]
That's why I did https://github.com/ga4gh-beacon/beacon-v2-Models/pull/63/commits/025c193bd8b268143c7d09fea7f1e158ec42f093 .

So he have either with plural `clinVarIds`:

```
clinVarIds:
  type: array
  items: string
  examples:
    - - id1
       - id1b
    - - other-id-format
       - another-one
```
or
```
clinVarIds:
  type: array
  items: string
  example:
    - id1
      id1b
```
or, when switching to a singular `clinVarId`
```
clinVarId:
  type: string
  examples:
    - id1
    - id1b
    - other-id-format
    - another-one
```
and w/ one example
```
clinVarId:
  type: string
  example: id1
```

**Comment by mbaudis** [comment]
... I **generally** prefer to use plural `examples` but both are correct. 

But the main point is: Is there a reason for multiple `clinVarIds`? If not, my proposal would be to change the name to `clinvarId` (previous note about pseudo-`caMel` in there) and then keep the list of `examples`.

**Comment by mrueda** [comment]
Speaking from a user/implementer point of view. 

Now, user’s are allowed to chose from the multiple ClinVar identifiers (e.g., accessions such as VCV, RCV,SCV or Variation ID), but then they’re forced to add only one of them in “clinVarId” field. This is translating the problem to the back-end.

See example at this link:
https://www.ncbi.nlm.nih.gov/clinvar/variation/9375/

An ideal solution would be to force users to store only **Variation ID** (integer), or to convert “clinVar” to an object and create nested properties within (e.g., Variation ID, SCV, RCV, SCV accession, etc.). This will alleviate queries at the back-end level.

m

**Comment by jrambla** [comment]
I'm refreshing my mind from this conversation, and I remember fearing that people uses a lot of different identifiers among the ones available (that refer to different aspects, but anyway...),but simply don't having experience to determine if by an array we are fostering incorrect/inconsistent reuse of the Ids or if that is the actual state-of-the-art for them.
@mrueda @mbaudis any opinion on that?

**Comment by mrueda** [comment]
ClinVar id is not something as used in the community as, say, dbSNP id. Everyone understands that dbSNP ids are “rs” and that’s what they’ll store and query (for dbSNP field.) 

On the other hand, if Beacon v2 provides freedom to populate “ClinVar id” with a variety of ClinVar identifiers (e.g., Variation ID, SCV, RCV, etc.) people will store and query whatever they have at hand. Note that this issue applies to a single value or to an array of values. The back-end will need to figure this out.

A solution could be either to enforce them to only store and query “Variation ID”, or to allow many values but in the form key-value. This is just a suggestion. It does not need to be addressed right now. 

Cheers,

m

**Comment by jrambla** [comment]
Do you have preference among the options you listed?


Jordi

**Comment by mrueda** [comment]
Variation ID

**Comment by mbaudis** [comment]
```
"clinvarId": {"id": "clinvar:12343", "description": "ClinVar variation id"}
```
or simple
```
"clinvarId": "12343"
```
or
```
"clinvarIds": [
  { "id": "clinvar:12343", "description": "ClinVar variation id"},
  { "id": "otherprefix:0987654", "description": "other var id"}
]
```
Also see the de-camelized parameter... @rahelp, @mrueda, @jrambla ?

**Comment by rahelp** [comment]
"clinvarIds": [
  { "id": "clinvar: 3144", "description": "ClinVar variation id"},
  { "id": "clinvar:VCV000003144.7", "description": "ClinVar accession id"}
]
since clinvar has both variation Id and Accession Id, I think it would make sense to represent it this way. (see example https://www.ncbi.nlm.nih.gov/clinvar/variation/3144/). Also, as pointed out some variants have several accession ids.

**Comment by jrambla** [comment]
@mbaudis could you look at my comment, please?

**Comment by mbaudis** [comment]
@jrambla @mrueda @rahelp Since we have the colliding interests in 1.) keeping things simple, 2.) being flexible, and 3.) using standards / prototypes wherever possible I have the proposal to:

* make the clinVarId single & explicit, and also changing the name to `clinvarVariantId`:
```
      "clinvarVariantId": {
        "description": "ClinVar variant id. Other id values used by ClinVar can be added to `variantAlternativeIds`",
        "pattern": "^(clinvar:)?\d+$",
        "type": "string",
        "examples": ["clinvar:12345", "9325"]
      }
```
* change the format of `variantAlternativeIds` to proper `externalReference` objects:
```
      "variantAlternativeIds": {
        "description": "List of cross-referencing ID(s), for the variant in other databases (e.g. dbSNP, ClinVar, ClinGen, COSMIC), as `externalReferences` with CURIE(s).",
        "type": "array",
        "items": {
          "$ref": "../common/externalReference.json"
        },
        "examples": [
          [
            {"id": "dbSNP:rs587780345", "reference": "https://www.ncbi.nlm.nih.gov/snp/rs587780345", "notes": "dbSNP id"},
            {"id": "ClinGen:CA152954", "reference": "http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA152954", "notes": "ClinGen Allele Registry id"},
            {"id": "UniProtKB:P35557#VAR_003699", "reference": "https://www.uniprot.org/uniprot/P35557#VAR_003699"}
          ],
          [
            {"id": "OMIM:164757.0001", "reference": "https://www.omim.org/entry/164757#0001"},
          ]
        ]
      },
```
This obviously breaks stuff, but so would any change of parameter name / format here. And we're probably very much in theoretical realm here, with the implementers mostly still prototyping - so better do this now.

(Side note: the `externalReference` schema had been lifted from Phenopackets; so this is another "GA4GH schema convergence" issue.)

But we can do the one w/o the other (i.e. only changing to `clinvarVariantId` - however, this leaves us with the messy "list of some identifiers in `variantAlternativeIds`.

**Comment by jrambla** [comment]
`clinvarVariantId` seems OK to me.
Using `externalReference` seems also OK to me. 
As no properties are required in `externalReference`, one `externalReference` with just the id would work. 
@mrueda any comment on the solution?

**Comment by mrueda** [comment]
No comments. All looks good. Thx.

**Comment by mbaudis** [comment]
So IMO mergeable, after the conflict fix (the one `examples` item that was updated in the meantime by @jrambla ...). Shall I?

**Comment by jrambla** [comment]
Yes, please

**Pull request merged**
